server:
  port : 8082
spring:
  application:
    name: helloworld
  profiles:
    active: db
  datasource:
    url: jdbc:sqlite:mydb.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin
  jpa:
    database-platform: com.example.helloWorld.dialect.SQLiteDialect
    hibernate.ddl-auto: update
    show-sql: false